from pathlib import Path

from profile_builder.builder import build_site
from profile_builder.config import Config, load_config
from profile_builder.utils import BuilderError
import pytest
from conftest import make_project


def test_build_creates_html_and_copies_assets(tmp_path):
    root = make_project(tmp_path)
    (root / "assets" / "resume.pdf").write_bytes(b"%PDF-1.4\n")
    (root / "profile.md").write_text("""---
name: Test Student
designation: PhD Scholar
institute: IIT Delhi
photo: assets/profile-placeholder.svg
cv: assets/resume.pdf
links:
  github: ""
research_interests: []
---
# About
Hello.
""", encoding="utf-8")
    output = build_site(root, Config())
    html = (output / "index.html").read_text(encoding="utf-8")
    assert "Test Student" in html
    assert 'href="./assets/template/css/style.css"' in html
    assert 'src="assets/user/profile-placeholder.svg"' in html
    assert 'href="assets/user/resume.pdf"' in html and ">Resume</a>" in html
    assert 'href="/assets/' not in html and 'src="/assets/' not in html
    assert (output / "assets" / "user" / "profile-placeholder.svg").is_file()
    assert (output / "assets" / "user" / "resume.pdf").is_file()
    assert (output / "assets" / "template" / "css" / "style.css").is_file()
    assert "Do not edit this file directly" in html


def test_build_cleans_previous_output(tmp_path):
    root = make_project(tmp_path)
    (root / "profile.md").write_text("---\nname: A\ndesignation: B\ninstitute: C\n---\nHi", encoding="utf-8")
    old = root / "dist"; old.mkdir(); (old / "old.txt").write_text("old")
    build_site(root)
    assert not (old / "old.txt").exists()


def test_build_retries_transient_windows_output_lock(tmp_path, monkeypatch):
    root = make_project(tmp_path)
    (root / "profile.md").write_text("---\nname: A\ndesignation: B\ninstitute: C\n---\nHi", encoding="utf-8")
    output = build_site(root)
    original_replace = Path.replace
    attempts = 0

    def transient_lock(path, target):
        nonlocal attempts
        if path == output and attempts == 0:
            attempts += 1
            error = PermissionError("preview file is in use")
            error.winerror = 32
            raise error
        return original_replace(path, target)

    monkeypatch.setattr(Path, "replace", transient_lock)
    build_site(root)
    assert attempts == 1
    assert (output / "index.html").is_file()


def test_failed_candidate_build_keeps_previous_valid_output(tmp_path, monkeypatch):
    root = make_project(tmp_path)
    (root / "profile.md").write_text("---\nname: A\ndesignation: B\ninstitute: C\n---\nHi", encoding="utf-8")
    output = build_site(root)
    before = (output / "index.html").read_bytes()

    class BrokenRenderer:
        def build(self, *_):
            raise BuilderError("candidate failed")

    monkeypatch.setattr("profile_builder.builder.renderer_for", lambda _: BrokenRenderer())
    with pytest.raises(BuilderError, match="candidate failed"):
        build_site(root)
    assert (output / "index.html").read_bytes() == before


def test_build_does_not_promote_private_temporary_workspace(tmp_path, monkeypatch):
    root = make_project(tmp_path)
    (root / "profile.md").write_text("---\nname: A\ndesignation: B\ninstitute: C\n---\nHi", encoding="utf-8")
    promoted = []
    original_promote = __import__("profile_builder.builder", fromlist=["_promote_output"])._promote_output

    def record_promote(source, output, previous):
        promoted.append(source)
        return original_promote(source, output, previous)

    monkeypatch.setattr("profile_builder.builder._promote_output", record_promote)
    output = build_site(root)
    assert promoted and promoted[0].parent == root
    assert promoted[0].name.startswith(".dist-publish-")
    assert not promoted[0].name.startswith(".dist-build-")
    assert (output / "index.html").is_file()


def test_config_rejects_source_directory_as_output(tmp_path):
    (tmp_path / "config.yml").write_text("template: basic\noutput_directory: assets\n", encoding="utf-8")
    with pytest.raises(BuilderError, match="protected source folder"):
        load_config(tmp_path / "config.yml")
