from dataclasses import dataclass
from pathlib import Path
from typing import Any
import json
import os
import re
import shutil
import tempfile
import time
import uuid

from .config import Config
from .context import create_context
from .profile import parse_profile
from .renderers import renderer_for
from .template_manifest import TemplateManifest
from .templates import TemplateRegistry
from .utils import BuilderError, confined_path

GENERATED_NOTICE = "<!-- Generated by Student Profile Builder. Do not edit this file directly; edit profile.md and rebuild. -->\n"


@dataclass(frozen=True)
class OutputIssue:
    path: str
    message: str


def build_site(project_root: Path, config: Config | None = None, *, template_id: str | None = None,
               profile_path: Path | None = None, output_directory: Path | None = None) -> Path:
    root = project_root.resolve()
    if config is None:
        from .config import load_config
        config = load_config(root / "config.yml")
    profile_file = _profile_path(root, profile_path or Path("profile.md"))
    profile = parse_profile(profile_file, root)
    template = TemplateRegistry(root / "templates").get(template_id or config.template)
    if profile.theme.enabled and not template.capabilities.get("theme_switching", False):
        raise BuilderError(f'The selected template "{template.name}" does not support light/dark theme switching. '
                           "Choose another template or disable theme switching.")
    output = output_directory.resolve() if output_directory else confined_path(root, config.output_directory, "Output directory")
    _guard_output(root, output)
    if output.exists() and output.is_symlink():
        raise BuilderError("Refusing to clean a symbolic-link output directory.")
    if output.exists() and not output.is_dir():
        raise BuilderError("Output path must be a directory.")
    output.parent.mkdir(parents=True, exist_ok=True)
    workspace = Path(tempfile.mkdtemp(prefix=f".{output.name}-build-", dir=output.parent))
    candidate = workspace / "candidate"
    publish = output.parent / f".{output.name}-publish-{uuid.uuid4().hex}"
    candidate.mkdir()
    try:
        context = create_context(profile, template)
        _normalize_asset_paths(context)
        renderer_for(template.engine).build(template, context, candidate)
        _copy_user_assets(root, candidate)
        _ensure_favicon(candidate)
        index = candidate / "index.html"
        if index.is_file():
            index.write_text(GENERATED_NOTICE + index.read_text(encoding="utf-8"), encoding="utf-8")
        issues = validate_output(candidate)
        if issues:
            raise BuilderError("Generated output validation failed:\n" + "\n".join(
                f"- {i.path}: {i.message}" for i in issues
            ))
        # tempfile creates a deliberately private directory on Windows.  Do
        # not rename that directory into the public preview location: doing so
        # would retain its restrictive ACL and make the GUI user's process see
        # valid generated files as missing.  A normally-created sibling
        # inherits the project permissions before it is promoted.
        publish.mkdir()
        shutil.copytree(candidate, publish, dirs_exist_ok=True)
        _promote_output(publish, output, workspace / "previous")
    finally:
        _remove_generated_workspace(publish)
        _remove_generated_workspace(workspace)
    if output == confined_path(root, config.output_directory, "Output directory"):
        from .build_state import record_build
        record_build(root, template.id)
    return output


def _promote_output(candidate: Path, output: Path, previous: Path) -> None:
    """Publish a complete candidate while retaining the last valid tree for rollback."""
    had_previous = output.exists()
    if had_previous:
        _replace_with_lock_retry(output, previous)
    try:
        _replace_with_lock_retry(candidate, output)
    except Exception:
        if had_previous and previous.exists() and not output.exists():
            _replace_with_lock_retry(previous, output)
        raise


def _replace_with_lock_retry(source: Path, target: Path, attempts: int = 8) -> None:
    """Retry the short-lived Windows sharing violations caused by the preview server."""
    for attempt in range(attempts):
        try:
            source.replace(target)
            return
        except OSError as error:
            transient = isinstance(error, PermissionError) or getattr(error, "winerror", None) in {5, 32, 145}
            if not transient:
                raise
            if attempt + 1 == attempts:
                raise BuilderError(
                    "The generated preview is temporarily in use. Please retry; the previous valid preview was kept."
                ) from error
            time.sleep(0.03 * (attempt + 1))


def _remove_generated_workspace(workspace: Path) -> None:
    """Best-effort cleanup for the exact internally-created staging directory."""
    if not workspace.exists():
        return
    for attempt in range(6):
        try:
            shutil.rmtree(workspace)
            return
        except FileNotFoundError:
            return
        except PermissionError:
            if attempt == 5:
                shutil.rmtree(workspace, ignore_errors=True)
                return
            time.sleep(0.03 * (attempt + 1))


def _ensure_favicon(output: Path) -> None:
    favicon=output/"favicon.svg"
    if not favicon.exists():
        favicon.write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#244f86"/><path d="M16 23l16-8 16 8-16 8zm5 5v12c7 5 15 5 22 0V28l-11 6z" fill="white"/></svg>',encoding="utf-8")
    managed=output/"assets/user/managed"; custom_icons=list(managed.glob("site-icon-*")) if managed.is_dir() else []
    chosen=custom_icons[0] if custom_icons else favicon
    for page in output.rglob("*.html"):
        text=page.read_text(encoding="utf-8")
        if "rel=\"icon\"" in text or "rel='icon'" in text: continue
        href=os.path.relpath(chosen,page.parent).replace("\\","/")
        tag=f'<link rel="icon" href="{href}">'
        if "</head>" in text: text=text.replace("</head>",tag+"</head>",1)
        else: text=tag+text
        page.write_text(text,encoding="utf-8")


def _profile_path(root: Path, path: Path) -> Path:
    candidate = (root / path).resolve() if not path.is_absolute() else path.resolve()
    if candidate != root and root not in candidate.parents:
        raise BuilderError(f"Profile path must stay inside the project: {path}")
    if not candidate.is_file(): raise BuilderError(f"Profile not found: {path}")
    return candidate


def _guard_output(root: Path, output: Path) -> None:
    if output == root or root not in output.parents: raise BuilderError("Output directory must stay inside the project.")
    first = output.relative_to(root).parts[0].lower()
    if first in {"assets", "templates", "src", "tests", "docs", ".git", ".venv", "examples"}:
        raise BuilderError(f'Output directory cannot be inside protected source folder "{first}".')


def _normalize_asset_paths(context: dict[str, Any]) -> None:
    profile = context["profile"]
    for field in ("photo", "cv", "icon"):
        value = profile.get(field)
        if value and Path(value).parts and Path(value).parts[0] == "assets":
            profile[field] = Path("assets", "user", *Path(value).parts[1:]).as_posix()
    context["site"]["icon"]=profile.get("icon","")


def _copy_user_assets(root: Path, output: Path) -> None:
    source = root / "assets"
    target = output / "assets" / "user"
    if source.is_dir(): shutil.copytree(source, target, dirs_exist_ok=True)


LOCAL_ABSOLUTE = re.compile(r"(?:[A-Za-z]:\\(?:Users|Projects)\\|/home/[^/\s]+/)", re.I)
ROOT_URL = re.compile(r"(?:src|href|url\()\s*=??\s*[\"']?/(?!/|#)", re.I)


def validate_output(output: Path) -> list[OutputIssue]:
    issues: list[OutputIssue] = []
    index = output / "index.html"
    if not index.is_file(): return [OutputIssue("index.html", "required output file is missing")]
    for path in output.rglob("*"):
        if path.is_file() and path.suffix.lower() in {".html", ".css", ".js", ".json"}:
            text = path.read_text(encoding="utf-8", errors="replace")
            if LOCAL_ABSOLUTE.search(text): issues.append(OutputIssue(path.relative_to(output).as_posix(), "contains a local absolute filesystem path"))
            if path.suffix.lower() in {".html", ".css"} and ROOT_URL.search(text):
                issues.append(OutputIssue(path.relative_to(output).as_posix(), "contains a root-relative local asset URL"))
    return issues
